# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Pty_QCH)

add_custom_target(KF5Pty_QCH)
set_target_properties(KF5Pty_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5Pty.tags"
    QHP_NAMESPACE "org.kde.KPty"
    QHP_NAMESPACE_VERSIONED "org.kde.KPty.5_58_0"
    QHP_VIRTUALFOLDER "kpty"
    IMPORTED TRUE
)
set_property(TARGET KF5Pty_QCH PROPERTY LINK_QCHS Qt5Core_QCH;KF5CoreAddons_QCH)

endif()
