# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dclement/EPITECH/second_year/OOP_indie_studio_2018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dclement/EPITECH/second_year/OOP_indie_studio_2018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dclement/EPITECH/second_year/OOP_indie_studio_2018/CMakeFiles /home/dclement/EPITECH/second_year/OOP_indie_studio_2018/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dclement/EPITECH/second_year/OOP_indie_studio_2018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

srcs/Core/Bomberman.o: srcs/Core/Bomberman.cpp.o

.PHONY : srcs/Core/Bomberman.o

# target to build an object file
srcs/Core/Bomberman.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Core/Bomberman.cpp.o
.PHONY : srcs/Core/Bomberman.cpp.o

srcs/Core/Bomberman.i: srcs/Core/Bomberman.cpp.i

.PHONY : srcs/Core/Bomberman.i

# target to preprocess a source file
srcs/Core/Bomberman.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Core/Bomberman.cpp.i
.PHONY : srcs/Core/Bomberman.cpp.i

srcs/Core/Bomberman.s: srcs/Core/Bomberman.cpp.s

.PHONY : srcs/Core/Bomberman.s

# target to generate assembly for a file
srcs/Core/Bomberman.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Core/Bomberman.cpp.s
.PHONY : srcs/Core/Bomberman.cpp.s

srcs/Game/Characters/ACharacter.o: srcs/Game/Characters/ACharacter.cpp.o

.PHONY : srcs/Game/Characters/ACharacter.o

# target to build an object file
srcs/Game/Characters/ACharacter.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/ACharacter.cpp.o
.PHONY : srcs/Game/Characters/ACharacter.cpp.o

srcs/Game/Characters/ACharacter.i: srcs/Game/Characters/ACharacter.cpp.i

.PHONY : srcs/Game/Characters/ACharacter.i

# target to preprocess a source file
srcs/Game/Characters/ACharacter.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/ACharacter.cpp.i
.PHONY : srcs/Game/Characters/ACharacter.cpp.i

srcs/Game/Characters/ACharacter.s: srcs/Game/Characters/ACharacter.cpp.s

.PHONY : srcs/Game/Characters/ACharacter.s

# target to generate assembly for a file
srcs/Game/Characters/ACharacter.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/ACharacter.cpp.s
.PHONY : srcs/Game/Characters/ACharacter.cpp.s

srcs/Game/Characters/Bot.o: srcs/Game/Characters/Bot.cpp.o

.PHONY : srcs/Game/Characters/Bot.o

# target to build an object file
srcs/Game/Characters/Bot.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/Bot.cpp.o
.PHONY : srcs/Game/Characters/Bot.cpp.o

srcs/Game/Characters/Bot.i: srcs/Game/Characters/Bot.cpp.i

.PHONY : srcs/Game/Characters/Bot.i

# target to preprocess a source file
srcs/Game/Characters/Bot.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/Bot.cpp.i
.PHONY : srcs/Game/Characters/Bot.cpp.i

srcs/Game/Characters/Bot.s: srcs/Game/Characters/Bot.cpp.s

.PHONY : srcs/Game/Characters/Bot.s

# target to generate assembly for a file
srcs/Game/Characters/Bot.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/Bot.cpp.s
.PHONY : srcs/Game/Characters/Bot.cpp.s

srcs/Game/Characters/Player.o: srcs/Game/Characters/Player.cpp.o

.PHONY : srcs/Game/Characters/Player.o

# target to build an object file
srcs/Game/Characters/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/Player.cpp.o
.PHONY : srcs/Game/Characters/Player.cpp.o

srcs/Game/Characters/Player.i: srcs/Game/Characters/Player.cpp.i

.PHONY : srcs/Game/Characters/Player.i

# target to preprocess a source file
srcs/Game/Characters/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/Player.cpp.i
.PHONY : srcs/Game/Characters/Player.cpp.i

srcs/Game/Characters/Player.s: srcs/Game/Characters/Player.cpp.s

.PHONY : srcs/Game/Characters/Player.s

# target to generate assembly for a file
srcs/Game/Characters/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Characters/Player.cpp.s
.PHONY : srcs/Game/Characters/Player.cpp.s

srcs/Game/Display/Display.o: srcs/Game/Display/Display.cpp.o

.PHONY : srcs/Game/Display/Display.o

# target to build an object file
srcs/Game/Display/Display.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Display/Display.cpp.o
.PHONY : srcs/Game/Display/Display.cpp.o

srcs/Game/Display/Display.i: srcs/Game/Display/Display.cpp.i

.PHONY : srcs/Game/Display/Display.i

# target to preprocess a source file
srcs/Game/Display/Display.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Display/Display.cpp.i
.PHONY : srcs/Game/Display/Display.cpp.i

srcs/Game/Display/Display.s: srcs/Game/Display/Display.cpp.s

.PHONY : srcs/Game/Display/Display.s

# target to generate assembly for a file
srcs/Game/Display/Display.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Display/Display.cpp.s
.PHONY : srcs/Game/Display/Display.cpp.s

srcs/Game/Display/DisplayLoader.o: srcs/Game/Display/DisplayLoader.cpp.o

.PHONY : srcs/Game/Display/DisplayLoader.o

# target to build an object file
srcs/Game/Display/DisplayLoader.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Display/DisplayLoader.cpp.o
.PHONY : srcs/Game/Display/DisplayLoader.cpp.o

srcs/Game/Display/DisplayLoader.i: srcs/Game/Display/DisplayLoader.cpp.i

.PHONY : srcs/Game/Display/DisplayLoader.i

# target to preprocess a source file
srcs/Game/Display/DisplayLoader.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Display/DisplayLoader.cpp.i
.PHONY : srcs/Game/Display/DisplayLoader.cpp.i

srcs/Game/Display/DisplayLoader.s: srcs/Game/Display/DisplayLoader.cpp.s

.PHONY : srcs/Game/Display/DisplayLoader.s

# target to generate assembly for a file
srcs/Game/Display/DisplayLoader.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Display/DisplayLoader.cpp.s
.PHONY : srcs/Game/Display/DisplayLoader.cpp.s

srcs/Game/Logic/Game.o: srcs/Game/Logic/Game.cpp.o

.PHONY : srcs/Game/Logic/Game.o

# target to build an object file
srcs/Game/Logic/Game.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Logic/Game.cpp.o
.PHONY : srcs/Game/Logic/Game.cpp.o

srcs/Game/Logic/Game.i: srcs/Game/Logic/Game.cpp.i

.PHONY : srcs/Game/Logic/Game.i

# target to preprocess a source file
srcs/Game/Logic/Game.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Logic/Game.cpp.i
.PHONY : srcs/Game/Logic/Game.cpp.i

srcs/Game/Logic/Game.s: srcs/Game/Logic/Game.cpp.s

.PHONY : srcs/Game/Logic/Game.s

# target to generate assembly for a file
srcs/Game/Logic/Game.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Logic/Game.cpp.s
.PHONY : srcs/Game/Logic/Game.cpp.s

srcs/Game/Map/ATile.o: srcs/Game/Map/ATile.cpp.o

.PHONY : srcs/Game/Map/ATile.o

# target to build an object file
srcs/Game/Map/ATile.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Map/ATile.cpp.o
.PHONY : srcs/Game/Map/ATile.cpp.o

srcs/Game/Map/ATile.i: srcs/Game/Map/ATile.cpp.i

.PHONY : srcs/Game/Map/ATile.i

# target to preprocess a source file
srcs/Game/Map/ATile.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Map/ATile.cpp.i
.PHONY : srcs/Game/Map/ATile.cpp.i

srcs/Game/Map/ATile.s: srcs/Game/Map/ATile.cpp.s

.PHONY : srcs/Game/Map/ATile.s

# target to generate assembly for a file
srcs/Game/Map/ATile.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Map/ATile.cpp.s
.PHONY : srcs/Game/Map/ATile.cpp.s

srcs/Game/Map/Map.o: srcs/Game/Map/Map.cpp.o

.PHONY : srcs/Game/Map/Map.o

# target to build an object file
srcs/Game/Map/Map.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Map/Map.cpp.o
.PHONY : srcs/Game/Map/Map.cpp.o

srcs/Game/Map/Map.i: srcs/Game/Map/Map.cpp.i

.PHONY : srcs/Game/Map/Map.i

# target to preprocess a source file
srcs/Game/Map/Map.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Map/Map.cpp.i
.PHONY : srcs/Game/Map/Map.cpp.i

srcs/Game/Map/Map.s: srcs/Game/Map/Map.cpp.s

.PHONY : srcs/Game/Map/Map.s

# target to generate assembly for a file
srcs/Game/Map/Map.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Map/Map.cpp.s
.PHONY : srcs/Game/Map/Map.cpp.s

srcs/Game/Menu/Menu.o: srcs/Game/Menu/Menu.cpp.o

.PHONY : srcs/Game/Menu/Menu.o

# target to build an object file
srcs/Game/Menu/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Menu/Menu.cpp.o
.PHONY : srcs/Game/Menu/Menu.cpp.o

srcs/Game/Menu/Menu.i: srcs/Game/Menu/Menu.cpp.i

.PHONY : srcs/Game/Menu/Menu.i

# target to preprocess a source file
srcs/Game/Menu/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Menu/Menu.cpp.i
.PHONY : srcs/Game/Menu/Menu.cpp.i

srcs/Game/Menu/Menu.s: srcs/Game/Menu/Menu.cpp.s

.PHONY : srcs/Game/Menu/Menu.s

# target to generate assembly for a file
srcs/Game/Menu/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Menu/Menu.cpp.s
.PHONY : srcs/Game/Menu/Menu.cpp.s

srcs/Game/Tool/Reader.o: srcs/Game/Tool/Reader.cpp.o

.PHONY : srcs/Game/Tool/Reader.o

# target to build an object file
srcs/Game/Tool/Reader.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Tool/Reader.cpp.o
.PHONY : srcs/Game/Tool/Reader.cpp.o

srcs/Game/Tool/Reader.i: srcs/Game/Tool/Reader.cpp.i

.PHONY : srcs/Game/Tool/Reader.i

# target to preprocess a source file
srcs/Game/Tool/Reader.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Tool/Reader.cpp.i
.PHONY : srcs/Game/Tool/Reader.cpp.i

srcs/Game/Tool/Reader.s: srcs/Game/Tool/Reader.cpp.s

.PHONY : srcs/Game/Tool/Reader.s

# target to generate assembly for a file
srcs/Game/Tool/Reader.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Game/Tool/Reader.cpp.s
.PHONY : srcs/Game/Tool/Reader.cpp.s

srcs/main.o: srcs/main.cpp.o

.PHONY : srcs/main.o

# target to build an object file
srcs/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/main.cpp.o
.PHONY : srcs/main.cpp.o

srcs/main.i: srcs/main.cpp.i

.PHONY : srcs/main.i

# target to preprocess a source file
srcs/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/main.cpp.i
.PHONY : srcs/main.cpp.i

srcs/main.s: srcs/main.cpp.s

.PHONY : srcs/main.s

# target to generate assembly for a file
srcs/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/main.cpp.s
.PHONY : srcs/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... srcs/Core/Bomberman.o"
	@echo "... srcs/Core/Bomberman.i"
	@echo "... srcs/Core/Bomberman.s"
	@echo "... srcs/Game/Characters/ACharacter.o"
	@echo "... srcs/Game/Characters/ACharacter.i"
	@echo "... srcs/Game/Characters/ACharacter.s"
	@echo "... srcs/Game/Characters/Bot.o"
	@echo "... srcs/Game/Characters/Bot.i"
	@echo "... srcs/Game/Characters/Bot.s"
	@echo "... srcs/Game/Characters/Player.o"
	@echo "... srcs/Game/Characters/Player.i"
	@echo "... srcs/Game/Characters/Player.s"
	@echo "... srcs/Game/Display/Display.o"
	@echo "... srcs/Game/Display/Display.i"
	@echo "... srcs/Game/Display/Display.s"
	@echo "... srcs/Game/Display/DisplayLoader.o"
	@echo "... srcs/Game/Display/DisplayLoader.i"
	@echo "... srcs/Game/Display/DisplayLoader.s"
	@echo "... srcs/Game/Logic/Game.o"
	@echo "... srcs/Game/Logic/Game.i"
	@echo "... srcs/Game/Logic/Game.s"
	@echo "... srcs/Game/Map/ATile.o"
	@echo "... srcs/Game/Map/ATile.i"
	@echo "... srcs/Game/Map/ATile.s"
	@echo "... srcs/Game/Map/Map.o"
	@echo "... srcs/Game/Map/Map.i"
	@echo "... srcs/Game/Map/Map.s"
	@echo "... srcs/Game/Menu/Menu.o"
	@echo "... srcs/Game/Menu/Menu.i"
	@echo "... srcs/Game/Menu/Menu.s"
	@echo "... srcs/Game/Tool/Reader.o"
	@echo "... srcs/Game/Tool/Reader.i"
	@echo "... srcs/Game/Tool/Reader.s"
	@echo "... srcs/main.o"
	@echo "... srcs/main.i"
	@echo "... srcs/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

