# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5WidgetsAddons_QCH)

add_custom_target(KF5WidgetsAddons_QCH)
set_target_properties(KF5WidgetsAddons_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5WidgetsAddons.tags"
    QHP_NAMESPACE "org.kde.KWidgetsAddons"
    QHP_NAMESPACE_VERSIONED "org.kde.KWidgetsAddons.5_58_0"
    QHP_VIRTUALFOLDER "kwidgetsaddons"
    IMPORTED TRUE
)
set_property(TARGET KF5WidgetsAddons_QCH PROPERTY LINK_QCHS Qt5Core_QCH;Qt5Gui_QCH;Qt5Widgets_QCH)

endif()
