# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Wallet_QCH)

add_custom_target(KF5Wallet_QCH)
set_target_properties(KF5Wallet_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5Wallet.tags"
    QHP_NAMESPACE "org.kde.KWallet"
    QHP_NAMESPACE_VERSIONED "org.kde.KWallet.5_58_0"
    QHP_VIRTUALFOLDER "kwallet"
    IMPORTED TRUE
)
set_property(TARGET KF5Wallet_QCH PROPERTY LINK_QCHS Qt5Gui_QCH)

endif()
