# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Parts_QCH)

add_custom_target(KF5Parts_QCH)
set_target_properties(KF5Parts_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5Parts.tags"
    QHP_NAMESPACE "org.kde.KParts"
    QHP_NAMESPACE_VERSIONED "org.kde.KParts.5_58_0"
    QHP_VIRTUALFOLDER "kparts"
    IMPORTED TRUE
)
set_property(TARGET KF5Parts_QCH PROPERTY LINK_QCHS KF5KIO_QCH;KF5XmlGui_QCH;KF5TextWidgets_QCH)

endif()
