# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5NotifyConfig_QCH)

add_custom_target(KF5NotifyConfig_QCH)
set_target_properties(KF5NotifyConfig_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5NotifyConfig.tags"
    QHP_NAMESPACE "org.kde.KNotifyConfig"
    QHP_NAMESPACE_VERSIONED "org.kde.KNotifyConfig.5_58_0"
    QHP_VIRTUALFOLDER "knotifyconfig"
    IMPORTED TRUE
)
set_property(TARGET KF5NotifyConfig_QCH PROPERTY LINK_QCHS Qt5Widgets_QCH)

endif()
