# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Archive_QCH)

add_custom_target(KF5Archive_QCH)
set_target_properties(KF5Archive_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5Archive.tags"
    QHP_NAMESPACE "org.kde.KArchive"
    QHP_NAMESPACE_VERSIONED "org.kde.KArchive.5_58_0"
    QHP_VIRTUALFOLDER "karchive"
    IMPORTED TRUE
)
set_property(TARGET KF5Archive_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()
