# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5NewStuff_QCH)

add_custom_target(KF5NewStuff_QCH)
set_target_properties(KF5NewStuff_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5NewStuff.tags"
    QHP_NAMESPACE "org.kde.KNewStuff"
    QHP_NAMESPACE_VERSIONED "org.kde.KNewStuff.5_58_0"
    QHP_VIRTUALFOLDER "knewstuff"
    IMPORTED TRUE
)
set_property(TARGET KF5NewStuff_QCH PROPERTY LINK_QCHS KF5NewStuffCore_QCH;KF5XmlGui_QCH;KF5Service_QCH;Qt5Widgets_QCH)

endif()
