# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5NewStuffCore_QCH)

add_custom_target(KF5NewStuffCore_QCH)
set_target_properties(KF5NewStuffCore_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5NewStuffCore.tags"
    QHP_NAMESPACE "org.kde.KNewStuffCore"
    QHP_NAMESPACE_VERSIONED "org.kde.KNewStuffCore.5_58_0"
    QHP_VIRTUALFOLDER "knewstuffcore"
    IMPORTED TRUE
)
set_property(TARGET KF5NewStuffCore_QCH PROPERTY LINK_QCHS KF5Attica_QCH;KF5CoreAddons_QCH)

endif()
