# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Wayland_QCH)

add_custom_target(KF5Wayland_QCH)
set_target_properties(KF5Wayland_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5Wayland.tags"
    QHP_NAMESPACE "org.kde.KWayland"
    QHP_NAMESPACE_VERSIONED "org.kde.KWayland.5_58_0"
    QHP_VIRTUALFOLDER "kwayland"
    IMPORTED TRUE
)
set_property(TARGET KF5Wayland_QCH PROPERTY LINK_QCHS Qt5Gui_QCH)

endif()
