# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5ItemModels_QCH)

add_custom_target(KF5ItemModels_QCH)
set_target_properties(KF5ItemModels_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/doc/qt/KF5ItemModels.tags"
    QHP_NAMESPACE "org.kde.KItemModels"
    QHP_NAMESPACE_VERSIONED "org.kde.KItemModels.5_58_0"
    QHP_VIRTUALFOLDER "kitemmodels"
    IMPORTED TRUE
)
set_property(TARGET KF5ItemModels_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()
